### ISSUE TITLE
Symbol's function definition is void: org-habit-parse-todo

### ISSUE THREAD

**Issue by zilti** [ryjm/habitrpg.el#10]
I get this error message when I want to `habitrpg-add` a TODO item tagged as :hrpgdaily:.

**Comment by ryjm** [comment]
Strange. Did you do a `(require 'habitrpg)`? That function is definitely defined - if you do a `C-h f habitrpg-mode` and navigate to the file where it's defined. Evaluate it  for a quick fix.

**Comment by zilti** [comment]
Yes, I did `(require 'habitrpg)`. And I can't find any definition of it in habitrpg.el, only a call to it on line 1416...

**Comment by ryjm** [comment]
Oh I know why - that's a function defined in org-habit.el. Do you have the org-habit module loaded?

**Comment by zilti** [comment]
Ahh I see! Yes, now I have it loaded, and that solves it. Thanks & sorry!
