### ISSUE TITLE
Error on habitrpg-add for dailies: void-function org-habit-done-dates

### ISSUE THREAD

**Issue by nvarnett** [ryjm/habitrpg.el#8]
I keep getting a void-function error when I try to add a daily to habitrpg using the default setup (which worked great!). I have tagged the headline with "hrpgdaily", and tried it with and without (repeating) scheduled dates. It seems likely this issue is on my end, and not with the org extension, but any help would be greatly appreciated. Here's a backtrace:

Debugger entered--Lisp error: (void-function org-habit-done-dates)
  (org-habit-done-dates (org-habit-parse-todo))
  (sort (org-habit-done-dates (org-habit-parse-todo)) (quote >))
  (car (sort (org-habit-done-dates (org-habit-parse-todo)) (quote >)))
  (days-to-time (car (sort (org-habit-done-dates (org-habit-parse-todo)) (quote >))))
  (decode-time (days-to-time (car (sort (org-habit-done-dates (org-habit-parse-todo)) (quote >)))))
  (nthcdr 3 (decode-time (days-to-time (car (sort (org-habit-done-dates (org-habit-parse-todo)) (quote >))))))
  (butlast (nthcdr 3 (decode-time (days-to-time (car (sort (org-habit-done-dates (org-habit-parse-todo)) (quote >)))))) 4)
  (if (member "hrpgdaily" (org-get-tags-at)) (butlast (nthcdr 3 (decode-time (days-to-time (car (sort (org-habit-done-dates ...) (quote >)))))) 4))
  (set v (if (member "hrpgdaily" (org-get-tags-at)) (butlast (nthcdr 3 (decode-time (days-to-time (car (sort ... ...))))) 4)))
  (let* ((v --cl-last-done-day--)) (set v (if (member "hrpgdaily" (org-get-tags-at)) (butlast (nthcdr 3 (decode-time (days-to-time (car ...)))) 4))))
  (let ((--cl-last-done-day-- (make-symbol "--last-done-day--"))) (let* ((v --cl-last-done-day--)) (set v (if (member "hrpgdaily" (org-get-tags-at)) (butlast (nthcdr 3 (decode-time (days-to-time ...))) 4)))) (progn (let ((--cl-type-- (make-symbol "--type--"))) (let* ((v --cl-type--)) (set v nil)) (progn (habitrpg-get-id (symbol-value --cl-task--) (list (quote lambda) (quote (&rest --cl-rest--)) (list (quote apply) (list ... ...) (list ... --cl-type--) (list ... --cl-last-done-day--) (list ... --cl-in-habit--) (list ... --cl-state--) (list ... --cl-task--) (quote --cl-rest--))))))))
  (progn (let ((--cl-last-done-day-- (make-symbol "--last-done-day--"))) (let* ((v --cl-last-done-day--)) (set v (if (member "hrpgdaily" (org-get-tags-at)) (butlast (nthcdr 3 (decode-time ...)) 4)))) (progn (let ((--cl-type-- (make-symbol "--type--"))) (let* ((v --cl-type--)) (set v nil)) (progn (habitrpg-get-id (symbol-value --cl-task--) (list (quote lambda) (quote ...) (list ... ... ... ... ... ... ... ...))))))))
  (let ((--cl-in-habit-- (make-symbol "--in-habit--"))) (let* ((v --cl-in-habit--)) (set v (org-entry-get-with-inheritance "IN_HABITRPG"))) (progn (let ((--cl-last-done-day-- (make-symbol "--last-done-day--"))) (let* ((v --cl-last-done-day--)) (set v (if (member "hrpgdaily" (org-get-tags-at)) (butlast (nthcdr 3 ...) 4)))) (progn (let ((--cl-type-- (make-symbol "--type--"))) (let* ((v --cl-type--)) (set v nil)) (progn (habitrpg-get-id (symbol-value --cl-task--) (list ... ... ...))))))))
  (progn (let ((--cl-in-habit-- (make-symbol "--in-habit--"))) (let* ((v --cl-in-habit--)) (set v (org-entry-get-with-inheritance "IN_HABITRPG"))) (progn (let ((--cl-last-done-day-- (make-symbol "--last-done-day--"))) (let* ((v --cl-last-done-day--)) (set v (if (member "hrpgdaily" ...) (butlast ... 4)))) (progn (let ((--cl-type-- ...)) (let* (...) (set v nil)) (progn (habitrpg-get-id ... ...))))))))
  (let ((--cl-state-- (make-symbol "--state--"))) (let* ((v --cl-state--)) (set v (nth 2 (org-heading-components)))) (progn (let ((--cl-in-habit-- (make-symbol "--in-habit--"))) (let* ((v --cl-in-habit--)) (set v (org-entry-get-with-inheritance "IN_HABITRPG"))) (progn (let ((--cl-last-done-day-- (make-symbol "--last-done-day--"))) (let* ((v --cl-last-done-day--)) (set v (if ... ...))) (progn (let (...) (let* ... ...) (progn ...))))))))
  (progn (let ((--cl-state-- (make-symbol "--state--"))) (let* ((v --cl-state--)) (set v (nth 2 (org-heading-components)))) (progn (let ((--cl-in-habit-- (make-symbol "--in-habit--"))) (let* ((v --cl-in-habit--)) (set v (org-entry-get-with-inheritance "IN_HABITRPG"))) (progn (let ((--cl-last-done-day-- ...)) (let* (...) (set v ...)) (progn (let ... ... ...))))))))
  (let ((--cl-task-- (make-symbol "--task--"))) (let* ((v --cl-task--)) (set v (nth 4 (org-heading-components)))) (progn (let ((--cl-state-- (make-symbol "--state--"))) (let* ((v --cl-state--)) (set v (nth 2 (org-heading-components)))) (progn (let ((--cl-in-habit-- (make-symbol "--in-habit--"))) (let* ((v --cl-in-habit--)) (set v (org-entry-get-with-inheritance "IN_HABITRPG"))) (progn (let (...) (let* ... ...) (progn ...))))))))
  (progn (if (string= major-mode (quote org-agenda-mode)) (org-agenda-switch-to)) (let ((--cl-task-- (make-symbol "--task--"))) (let* ((v --cl-task--)) (set v (nth 4 (org-heading-components)))) (progn (let ((--cl-state-- (make-symbol "--state--"))) (let* ((v --cl-state--)) (set v (nth 2 (org-heading-components)))) (progn (let ((--cl-in-habit-- ...)) (let* (...) (set v ...)) (progn (let ... ... ...))))))))
  (unwind-protect (progn (if (string= major-mode (quote org-agenda-mode)) (org-agenda-switch-to)) (let ((--cl-task-- (make-symbol "--task--"))) (let* ((v --cl-task--)) (set v (nth 4 (org-heading-components)))) (progn (let ((--cl-state-- (make-symbol "--state--"))) (let* ((v --cl-state--)) (set v (nth 2 ...))) (progn (let (...) (let* ... ...) (progn ...))))))) (set-window-configuration wconfig))
  (let ((wconfig (current-window-configuration))) (unwind-protect (progn (if (string= major-mode (quote org-agenda-mode)) (org-agenda-switch-to)) (let ((--cl-task-- (make-symbol "--task--"))) (let* ((v --cl-task--)) (set v (nth 4 (org-heading-components)))) (progn (let ((--cl-state-- ...)) (let* (...) (set v ...)) (progn (let ... ... ...)))))) (set-window-configuration wconfig)))
  (save-excursion (let ((wconfig (current-window-configuration))) (unwind-protect (progn (if (string= major-mode (quote org-agenda-mode)) (org-agenda-switch-to)) (let ((--cl-task-- (make-symbol "--task--"))) (let* ((v --cl-task--)) (set v (nth 4 ...))) (progn (let (...) (let* ... ...) (progn ...))))) (set-window-configuration wconfig))))
  habitrpg-add()
  call-interactively(habitrpg-add nil nil)

**Comment by ryjm** [comment]
Totally forgot to respond to this. Did you figure it out? `org-habit-done-dates` is a function in `org-habit.el`. Maybe you didn't load the org-habit module?
